//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 5.0.61118.0
// 
namespace SilverlightApplication.EmpleadosServiceReference {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="empleado", Namespace="http://schemas.datacontract.org/2004/07/TareaServiceWebRole")]
    public partial class empleado : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idEmpleadoField;
        
        private string nbrEmpleadoField;
        
        private System.Nullable<int> idDeptoField;
        
        private System.DateTime fechaIngresoField;
        
        private SilverlightApplication.EmpleadosServiceReference.Binary fotoField;
        
        private System.Collections.ObjectModel.ObservableCollection<SilverlightApplication.EmpleadosServiceReference.departamento> departamentosField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idEmpleado {
            get {
                return this.idEmpleadoField;
            }
            set {
                if ((this.idEmpleadoField.Equals(value) != true)) {
                    this.idEmpleadoField = value;
                    this.RaisePropertyChanged("idEmpleado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nbrEmpleado {
            get {
                return this.nbrEmpleadoField;
            }
            set {
                if ((object.ReferenceEquals(this.nbrEmpleadoField, value) != true)) {
                    this.nbrEmpleadoField = value;
                    this.RaisePropertyChanged("nbrEmpleado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.Nullable<int> idDepto {
            get {
                return this.idDeptoField;
            }
            set {
                if ((this.idDeptoField.Equals(value) != true)) {
                    this.idDeptoField = value;
                    this.RaisePropertyChanged("idDepto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.DateTime fechaIngreso {
            get {
                return this.fechaIngresoField;
            }
            set {
                if ((this.fechaIngresoField.Equals(value) != true)) {
                    this.fechaIngresoField = value;
                    this.RaisePropertyChanged("fechaIngreso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public SilverlightApplication.EmpleadosServiceReference.Binary foto {
            get {
                return this.fotoField;
            }
            set {
                if ((object.ReferenceEquals(this.fotoField, value) != true)) {
                    this.fotoField = value;
                    this.RaisePropertyChanged("foto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public System.Collections.ObjectModel.ObservableCollection<SilverlightApplication.EmpleadosServiceReference.departamento> departamentos {
            get {
                return this.departamentosField;
            }
            set {
                if ((object.ReferenceEquals(this.departamentosField, value) != true)) {
                    this.departamentosField = value;
                    this.RaisePropertyChanged("departamentos");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Binary", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Linq")]
    public partial class Binary : object, System.ComponentModel.INotifyPropertyChanged {
        
        private byte[] BytesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Bytes {
            get {
                return this.BytesField;
            }
            set {
                if ((object.ReferenceEquals(this.BytesField, value) != true)) {
                    this.BytesField = value;
                    this.RaisePropertyChanged("Bytes");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="departamento", Namespace="http://schemas.datacontract.org/2004/07/TareaServiceWebRole")]
    public partial class departamento : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idDeptoField;
        
        private string nbrDeptoField;
        
        private System.Nullable<int> idEncargadoField;
        
        private string ubicacionField;
        
        private System.Collections.ObjectModel.ObservableCollection<SilverlightApplication.EmpleadosServiceReference.empleado> empleadosField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idDepto {
            get {
                return this.idDeptoField;
            }
            set {
                if ((this.idDeptoField.Equals(value) != true)) {
                    this.idDeptoField = value;
                    this.RaisePropertyChanged("idDepto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nbrDepto {
            get {
                return this.nbrDeptoField;
            }
            set {
                if ((object.ReferenceEquals(this.nbrDeptoField, value) != true)) {
                    this.nbrDeptoField = value;
                    this.RaisePropertyChanged("nbrDepto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.Nullable<int> idEncargado {
            get {
                return this.idEncargadoField;
            }
            set {
                if ((this.idEncargadoField.Equals(value) != true)) {
                    this.idEncargadoField = value;
                    this.RaisePropertyChanged("idEncargado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string ubicacion {
            get {
                return this.ubicacionField;
            }
            set {
                if ((object.ReferenceEquals(this.ubicacionField, value) != true)) {
                    this.ubicacionField = value;
                    this.RaisePropertyChanged("ubicacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public System.Collections.ObjectModel.ObservableCollection<SilverlightApplication.EmpleadosServiceReference.empleado> empleados {
            get {
                return this.empleadosField;
            }
            set {
                if ((object.ReferenceEquals(this.empleadosField, value) != true)) {
                    this.empleadosField = value;
                    this.RaisePropertyChanged("empleados");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EmpleadosServiceReference.IEmpleadosService")]
    public interface IEmpleadosService {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IEmpleadosService/agregarNuevoEmpleado", ReplyAction="http://tempuri.org/IEmpleadosService/agregarNuevoEmpleadoResponse")]
        System.IAsyncResult BeginagregarNuevoEmpleado(SilverlightApplication.EmpleadosServiceReference.empleado nuevoEmpleado, System.AsyncCallback callback, object asyncState);
        
        bool EndagregarNuevoEmpleado(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IEmpleadosService/eliminarEmpleado", ReplyAction="http://tempuri.org/IEmpleadosService/eliminarEmpleadoResponse")]
        System.IAsyncResult BegineliminarEmpleado(int empleadoID, System.AsyncCallback callback, object asyncState);
        
        bool EndeliminarEmpleado(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IEmpleadosService/modificarEmpleado", ReplyAction="http://tempuri.org/IEmpleadosService/modificarEmpleadoResponse")]
        System.IAsyncResult BeginmodificarEmpleado(SilverlightApplication.EmpleadosServiceReference.empleado nuevoEmpleado, System.AsyncCallback callback, object asyncState);
        
        bool EndmodificarEmpleado(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IEmpleadosService/getEmpleados", ReplyAction="http://tempuri.org/IEmpleadosService/getEmpleadosResponse")]
        System.IAsyncResult BegingetEmpleados(System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<SilverlightApplication.EmpleadosServiceReference.empleado> EndgetEmpleados(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IEmpleadosService/getEmpleadosDepartamento", ReplyAction="http://tempuri.org/IEmpleadosService/getEmpleadosDepartamentoResponse")]
        System.IAsyncResult BegingetEmpleadosDepartamento(SilverlightApplication.EmpleadosServiceReference.empleado buscarEmpleado, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<SilverlightApplication.EmpleadosServiceReference.empleado> EndgetEmpleadosDepartamento(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEmpleadosServiceChannel : SilverlightApplication.EmpleadosServiceReference.IEmpleadosService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class agregarNuevoEmpleadoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public agregarNuevoEmpleadoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class eliminarEmpleadoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public eliminarEmpleadoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class modificarEmpleadoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public modificarEmpleadoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getEmpleadosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public getEmpleadosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<SilverlightApplication.EmpleadosServiceReference.empleado> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<SilverlightApplication.EmpleadosServiceReference.empleado>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getEmpleadosDepartamentoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public getEmpleadosDepartamentoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<SilverlightApplication.EmpleadosServiceReference.empleado> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<SilverlightApplication.EmpleadosServiceReference.empleado>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmpleadosServiceClient : System.ServiceModel.ClientBase<SilverlightApplication.EmpleadosServiceReference.IEmpleadosService>, SilverlightApplication.EmpleadosServiceReference.IEmpleadosService {
        
        private BeginOperationDelegate onBeginagregarNuevoEmpleadoDelegate;
        
        private EndOperationDelegate onEndagregarNuevoEmpleadoDelegate;
        
        private System.Threading.SendOrPostCallback onagregarNuevoEmpleadoCompletedDelegate;
        
        private BeginOperationDelegate onBegineliminarEmpleadoDelegate;
        
        private EndOperationDelegate onEndeliminarEmpleadoDelegate;
        
        private System.Threading.SendOrPostCallback oneliminarEmpleadoCompletedDelegate;
        
        private BeginOperationDelegate onBeginmodificarEmpleadoDelegate;
        
        private EndOperationDelegate onEndmodificarEmpleadoDelegate;
        
        private System.Threading.SendOrPostCallback onmodificarEmpleadoCompletedDelegate;
        
        private BeginOperationDelegate onBegingetEmpleadosDelegate;
        
        private EndOperationDelegate onEndgetEmpleadosDelegate;
        
        private System.Threading.SendOrPostCallback ongetEmpleadosCompletedDelegate;
        
        private BeginOperationDelegate onBegingetEmpleadosDepartamentoDelegate;
        
        private EndOperationDelegate onEndgetEmpleadosDepartamentoDelegate;
        
        private System.Threading.SendOrPostCallback ongetEmpleadosDepartamentoCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public EmpleadosServiceClient() {
        }
        
        public EmpleadosServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmpleadosServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmpleadosServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmpleadosServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<agregarNuevoEmpleadoCompletedEventArgs> agregarNuevoEmpleadoCompleted;
        
        public event System.EventHandler<eliminarEmpleadoCompletedEventArgs> eliminarEmpleadoCompleted;
        
        public event System.EventHandler<modificarEmpleadoCompletedEventArgs> modificarEmpleadoCompleted;
        
        public event System.EventHandler<getEmpleadosCompletedEventArgs> getEmpleadosCompleted;
        
        public event System.EventHandler<getEmpleadosDepartamentoCompletedEventArgs> getEmpleadosDepartamentoCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SilverlightApplication.EmpleadosServiceReference.IEmpleadosService.BeginagregarNuevoEmpleado(SilverlightApplication.EmpleadosServiceReference.empleado nuevoEmpleado, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginagregarNuevoEmpleado(nuevoEmpleado, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bool SilverlightApplication.EmpleadosServiceReference.IEmpleadosService.EndagregarNuevoEmpleado(System.IAsyncResult result) {
            return base.Channel.EndagregarNuevoEmpleado(result);
        }
        
        private System.IAsyncResult OnBeginagregarNuevoEmpleado(object[] inValues, System.AsyncCallback callback, object asyncState) {
            SilverlightApplication.EmpleadosServiceReference.empleado nuevoEmpleado = ((SilverlightApplication.EmpleadosServiceReference.empleado)(inValues[0]));
            return ((SilverlightApplication.EmpleadosServiceReference.IEmpleadosService)(this)).BeginagregarNuevoEmpleado(nuevoEmpleado, callback, asyncState);
        }
        
        private object[] OnEndagregarNuevoEmpleado(System.IAsyncResult result) {
            bool retVal = ((SilverlightApplication.EmpleadosServiceReference.IEmpleadosService)(this)).EndagregarNuevoEmpleado(result);
            return new object[] {
                    retVal};
        }
        
        private void OnagregarNuevoEmpleadoCompleted(object state) {
            if ((this.agregarNuevoEmpleadoCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.agregarNuevoEmpleadoCompleted(this, new agregarNuevoEmpleadoCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void agregarNuevoEmpleadoAsync(SilverlightApplication.EmpleadosServiceReference.empleado nuevoEmpleado) {
            this.agregarNuevoEmpleadoAsync(nuevoEmpleado, null);
        }
        
        public void agregarNuevoEmpleadoAsync(SilverlightApplication.EmpleadosServiceReference.empleado nuevoEmpleado, object userState) {
            if ((this.onBeginagregarNuevoEmpleadoDelegate == null)) {
                this.onBeginagregarNuevoEmpleadoDelegate = new BeginOperationDelegate(this.OnBeginagregarNuevoEmpleado);
            }
            if ((this.onEndagregarNuevoEmpleadoDelegate == null)) {
                this.onEndagregarNuevoEmpleadoDelegate = new EndOperationDelegate(this.OnEndagregarNuevoEmpleado);
            }
            if ((this.onagregarNuevoEmpleadoCompletedDelegate == null)) {
                this.onagregarNuevoEmpleadoCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnagregarNuevoEmpleadoCompleted);
            }
            base.InvokeAsync(this.onBeginagregarNuevoEmpleadoDelegate, new object[] {
                        nuevoEmpleado}, this.onEndagregarNuevoEmpleadoDelegate, this.onagregarNuevoEmpleadoCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SilverlightApplication.EmpleadosServiceReference.IEmpleadosService.BegineliminarEmpleado(int empleadoID, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegineliminarEmpleado(empleadoID, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bool SilverlightApplication.EmpleadosServiceReference.IEmpleadosService.EndeliminarEmpleado(System.IAsyncResult result) {
            return base.Channel.EndeliminarEmpleado(result);
        }
        
        private System.IAsyncResult OnBegineliminarEmpleado(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int empleadoID = ((int)(inValues[0]));
            return ((SilverlightApplication.EmpleadosServiceReference.IEmpleadosService)(this)).BegineliminarEmpleado(empleadoID, callback, asyncState);
        }
        
        private object[] OnEndeliminarEmpleado(System.IAsyncResult result) {
            bool retVal = ((SilverlightApplication.EmpleadosServiceReference.IEmpleadosService)(this)).EndeliminarEmpleado(result);
            return new object[] {
                    retVal};
        }
        
        private void OneliminarEmpleadoCompleted(object state) {
            if ((this.eliminarEmpleadoCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.eliminarEmpleadoCompleted(this, new eliminarEmpleadoCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void eliminarEmpleadoAsync(int empleadoID) {
            this.eliminarEmpleadoAsync(empleadoID, null);
        }
        
        public void eliminarEmpleadoAsync(int empleadoID, object userState) {
            if ((this.onBegineliminarEmpleadoDelegate == null)) {
                this.onBegineliminarEmpleadoDelegate = new BeginOperationDelegate(this.OnBegineliminarEmpleado);
            }
            if ((this.onEndeliminarEmpleadoDelegate == null)) {
                this.onEndeliminarEmpleadoDelegate = new EndOperationDelegate(this.OnEndeliminarEmpleado);
            }
            if ((this.oneliminarEmpleadoCompletedDelegate == null)) {
                this.oneliminarEmpleadoCompletedDelegate = new System.Threading.SendOrPostCallback(this.OneliminarEmpleadoCompleted);
            }
            base.InvokeAsync(this.onBegineliminarEmpleadoDelegate, new object[] {
                        empleadoID}, this.onEndeliminarEmpleadoDelegate, this.oneliminarEmpleadoCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SilverlightApplication.EmpleadosServiceReference.IEmpleadosService.BeginmodificarEmpleado(SilverlightApplication.EmpleadosServiceReference.empleado nuevoEmpleado, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginmodificarEmpleado(nuevoEmpleado, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bool SilverlightApplication.EmpleadosServiceReference.IEmpleadosService.EndmodificarEmpleado(System.IAsyncResult result) {
            return base.Channel.EndmodificarEmpleado(result);
        }
        
        private System.IAsyncResult OnBeginmodificarEmpleado(object[] inValues, System.AsyncCallback callback, object asyncState) {
            SilverlightApplication.EmpleadosServiceReference.empleado nuevoEmpleado = ((SilverlightApplication.EmpleadosServiceReference.empleado)(inValues[0]));
            return ((SilverlightApplication.EmpleadosServiceReference.IEmpleadosService)(this)).BeginmodificarEmpleado(nuevoEmpleado, callback, asyncState);
        }
        
        private object[] OnEndmodificarEmpleado(System.IAsyncResult result) {
            bool retVal = ((SilverlightApplication.EmpleadosServiceReference.IEmpleadosService)(this)).EndmodificarEmpleado(result);
            return new object[] {
                    retVal};
        }
        
        private void OnmodificarEmpleadoCompleted(object state) {
            if ((this.modificarEmpleadoCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.modificarEmpleadoCompleted(this, new modificarEmpleadoCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void modificarEmpleadoAsync(SilverlightApplication.EmpleadosServiceReference.empleado nuevoEmpleado) {
            this.modificarEmpleadoAsync(nuevoEmpleado, null);
        }
        
        public void modificarEmpleadoAsync(SilverlightApplication.EmpleadosServiceReference.empleado nuevoEmpleado, object userState) {
            if ((this.onBeginmodificarEmpleadoDelegate == null)) {
                this.onBeginmodificarEmpleadoDelegate = new BeginOperationDelegate(this.OnBeginmodificarEmpleado);
            }
            if ((this.onEndmodificarEmpleadoDelegate == null)) {
                this.onEndmodificarEmpleadoDelegate = new EndOperationDelegate(this.OnEndmodificarEmpleado);
            }
            if ((this.onmodificarEmpleadoCompletedDelegate == null)) {
                this.onmodificarEmpleadoCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnmodificarEmpleadoCompleted);
            }
            base.InvokeAsync(this.onBeginmodificarEmpleadoDelegate, new object[] {
                        nuevoEmpleado}, this.onEndmodificarEmpleadoDelegate, this.onmodificarEmpleadoCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SilverlightApplication.EmpleadosServiceReference.IEmpleadosService.BegingetEmpleados(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegingetEmpleados(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<SilverlightApplication.EmpleadosServiceReference.empleado> SilverlightApplication.EmpleadosServiceReference.IEmpleadosService.EndgetEmpleados(System.IAsyncResult result) {
            return base.Channel.EndgetEmpleados(result);
        }
        
        private System.IAsyncResult OnBegingetEmpleados(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((SilverlightApplication.EmpleadosServiceReference.IEmpleadosService)(this)).BegingetEmpleados(callback, asyncState);
        }
        
        private object[] OnEndgetEmpleados(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<SilverlightApplication.EmpleadosServiceReference.empleado> retVal = ((SilverlightApplication.EmpleadosServiceReference.IEmpleadosService)(this)).EndgetEmpleados(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetEmpleadosCompleted(object state) {
            if ((this.getEmpleadosCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getEmpleadosCompleted(this, new getEmpleadosCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getEmpleadosAsync() {
            this.getEmpleadosAsync(null);
        }
        
        public void getEmpleadosAsync(object userState) {
            if ((this.onBegingetEmpleadosDelegate == null)) {
                this.onBegingetEmpleadosDelegate = new BeginOperationDelegate(this.OnBegingetEmpleados);
            }
            if ((this.onEndgetEmpleadosDelegate == null)) {
                this.onEndgetEmpleadosDelegate = new EndOperationDelegate(this.OnEndgetEmpleados);
            }
            if ((this.ongetEmpleadosCompletedDelegate == null)) {
                this.ongetEmpleadosCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetEmpleadosCompleted);
            }
            base.InvokeAsync(this.onBegingetEmpleadosDelegate, null, this.onEndgetEmpleadosDelegate, this.ongetEmpleadosCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SilverlightApplication.EmpleadosServiceReference.IEmpleadosService.BegingetEmpleadosDepartamento(SilverlightApplication.EmpleadosServiceReference.empleado buscarEmpleado, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegingetEmpleadosDepartamento(buscarEmpleado, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<SilverlightApplication.EmpleadosServiceReference.empleado> SilverlightApplication.EmpleadosServiceReference.IEmpleadosService.EndgetEmpleadosDepartamento(System.IAsyncResult result) {
            return base.Channel.EndgetEmpleadosDepartamento(result);
        }
        
        private System.IAsyncResult OnBegingetEmpleadosDepartamento(object[] inValues, System.AsyncCallback callback, object asyncState) {
            SilverlightApplication.EmpleadosServiceReference.empleado buscarEmpleado = ((SilverlightApplication.EmpleadosServiceReference.empleado)(inValues[0]));
            return ((SilverlightApplication.EmpleadosServiceReference.IEmpleadosService)(this)).BegingetEmpleadosDepartamento(buscarEmpleado, callback, asyncState);
        }
        
        private object[] OnEndgetEmpleadosDepartamento(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<SilverlightApplication.EmpleadosServiceReference.empleado> retVal = ((SilverlightApplication.EmpleadosServiceReference.IEmpleadosService)(this)).EndgetEmpleadosDepartamento(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetEmpleadosDepartamentoCompleted(object state) {
            if ((this.getEmpleadosDepartamentoCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getEmpleadosDepartamentoCompleted(this, new getEmpleadosDepartamentoCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getEmpleadosDepartamentoAsync(SilverlightApplication.EmpleadosServiceReference.empleado buscarEmpleado) {
            this.getEmpleadosDepartamentoAsync(buscarEmpleado, null);
        }
        
        public void getEmpleadosDepartamentoAsync(SilverlightApplication.EmpleadosServiceReference.empleado buscarEmpleado, object userState) {
            if ((this.onBegingetEmpleadosDepartamentoDelegate == null)) {
                this.onBegingetEmpleadosDepartamentoDelegate = new BeginOperationDelegate(this.OnBegingetEmpleadosDepartamento);
            }
            if ((this.onEndgetEmpleadosDepartamentoDelegate == null)) {
                this.onEndgetEmpleadosDepartamentoDelegate = new EndOperationDelegate(this.OnEndgetEmpleadosDepartamento);
            }
            if ((this.ongetEmpleadosDepartamentoCompletedDelegate == null)) {
                this.ongetEmpleadosDepartamentoCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetEmpleadosDepartamentoCompleted);
            }
            base.InvokeAsync(this.onBegingetEmpleadosDepartamentoDelegate, new object[] {
                        buscarEmpleado}, this.onEndgetEmpleadosDepartamentoDelegate, this.ongetEmpleadosDepartamentoCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override SilverlightApplication.EmpleadosServiceReference.IEmpleadosService CreateChannel() {
            return new EmpleadosServiceClientChannel(this);
        }
        
        private class EmpleadosServiceClientChannel : ChannelBase<SilverlightApplication.EmpleadosServiceReference.IEmpleadosService>, SilverlightApplication.EmpleadosServiceReference.IEmpleadosService {
            
            public EmpleadosServiceClientChannel(System.ServiceModel.ClientBase<SilverlightApplication.EmpleadosServiceReference.IEmpleadosService> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginagregarNuevoEmpleado(SilverlightApplication.EmpleadosServiceReference.empleado nuevoEmpleado, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = nuevoEmpleado;
                System.IAsyncResult _result = base.BeginInvoke("agregarNuevoEmpleado", _args, callback, asyncState);
                return _result;
            }
            
            public bool EndagregarNuevoEmpleado(System.IAsyncResult result) {
                object[] _args = new object[0];
                bool _result = ((bool)(base.EndInvoke("agregarNuevoEmpleado", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BegineliminarEmpleado(int empleadoID, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = empleadoID;
                System.IAsyncResult _result = base.BeginInvoke("eliminarEmpleado", _args, callback, asyncState);
                return _result;
            }
            
            public bool EndeliminarEmpleado(System.IAsyncResult result) {
                object[] _args = new object[0];
                bool _result = ((bool)(base.EndInvoke("eliminarEmpleado", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginmodificarEmpleado(SilverlightApplication.EmpleadosServiceReference.empleado nuevoEmpleado, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = nuevoEmpleado;
                System.IAsyncResult _result = base.BeginInvoke("modificarEmpleado", _args, callback, asyncState);
                return _result;
            }
            
            public bool EndmodificarEmpleado(System.IAsyncResult result) {
                object[] _args = new object[0];
                bool _result = ((bool)(base.EndInvoke("modificarEmpleado", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BegingetEmpleados(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("getEmpleados", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<SilverlightApplication.EmpleadosServiceReference.empleado> EndgetEmpleados(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<SilverlightApplication.EmpleadosServiceReference.empleado> _result = ((System.Collections.ObjectModel.ObservableCollection<SilverlightApplication.EmpleadosServiceReference.empleado>)(base.EndInvoke("getEmpleados", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BegingetEmpleadosDepartamento(SilverlightApplication.EmpleadosServiceReference.empleado buscarEmpleado, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = buscarEmpleado;
                System.IAsyncResult _result = base.BeginInvoke("getEmpleadosDepartamento", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<SilverlightApplication.EmpleadosServiceReference.empleado> EndgetEmpleadosDepartamento(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<SilverlightApplication.EmpleadosServiceReference.empleado> _result = ((System.Collections.ObjectModel.ObservableCollection<SilverlightApplication.EmpleadosServiceReference.empleado>)(base.EndInvoke("getEmpleadosDepartamento", _args, result)));
                return _result;
            }
        }
    }
}
