//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 5.0.61118.0
// 
namespace SilverlightApplication.DepartamentosServiceReference {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="departamento", Namespace="http://schemas.datacontract.org/2004/07/TareaServiceWebRole")]
    public partial class departamento : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idDeptoField;
        
        private string nbrDeptoField;
        
        private System.Nullable<int> idEncargadoField;
        
        private string ubicacionField;
        
        private System.Collections.ObjectModel.ObservableCollection<SilverlightApplication.DepartamentosServiceReference.empleado> empleadosField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idDepto {
            get {
                return this.idDeptoField;
            }
            set {
                if ((this.idDeptoField.Equals(value) != true)) {
                    this.idDeptoField = value;
                    this.RaisePropertyChanged("idDepto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nbrDepto {
            get {
                return this.nbrDeptoField;
            }
            set {
                if ((object.ReferenceEquals(this.nbrDeptoField, value) != true)) {
                    this.nbrDeptoField = value;
                    this.RaisePropertyChanged("nbrDepto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.Nullable<int> idEncargado {
            get {
                return this.idEncargadoField;
            }
            set {
                if ((this.idEncargadoField.Equals(value) != true)) {
                    this.idEncargadoField = value;
                    this.RaisePropertyChanged("idEncargado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string ubicacion {
            get {
                return this.ubicacionField;
            }
            set {
                if ((object.ReferenceEquals(this.ubicacionField, value) != true)) {
                    this.ubicacionField = value;
                    this.RaisePropertyChanged("ubicacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public System.Collections.ObjectModel.ObservableCollection<SilverlightApplication.DepartamentosServiceReference.empleado> empleados {
            get {
                return this.empleadosField;
            }
            set {
                if ((object.ReferenceEquals(this.empleadosField, value) != true)) {
                    this.empleadosField = value;
                    this.RaisePropertyChanged("empleados");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="empleado", Namespace="http://schemas.datacontract.org/2004/07/TareaServiceWebRole")]
    public partial class empleado : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idEmpleadoField;
        
        private string nbrEmpleadoField;
        
        private System.Nullable<int> idDeptoField;
        
        private System.DateTime fechaIngresoField;
        
        private SilverlightApplication.DepartamentosServiceReference.Binary fotoField;
        
        private System.Collections.ObjectModel.ObservableCollection<SilverlightApplication.DepartamentosServiceReference.departamento> departamentosField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idEmpleado {
            get {
                return this.idEmpleadoField;
            }
            set {
                if ((this.idEmpleadoField.Equals(value) != true)) {
                    this.idEmpleadoField = value;
                    this.RaisePropertyChanged("idEmpleado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nbrEmpleado {
            get {
                return this.nbrEmpleadoField;
            }
            set {
                if ((object.ReferenceEquals(this.nbrEmpleadoField, value) != true)) {
                    this.nbrEmpleadoField = value;
                    this.RaisePropertyChanged("nbrEmpleado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.Nullable<int> idDepto {
            get {
                return this.idDeptoField;
            }
            set {
                if ((this.idDeptoField.Equals(value) != true)) {
                    this.idDeptoField = value;
                    this.RaisePropertyChanged("idDepto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.DateTime fechaIngreso {
            get {
                return this.fechaIngresoField;
            }
            set {
                if ((this.fechaIngresoField.Equals(value) != true)) {
                    this.fechaIngresoField = value;
                    this.RaisePropertyChanged("fechaIngreso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public SilverlightApplication.DepartamentosServiceReference.Binary foto {
            get {
                return this.fotoField;
            }
            set {
                if ((object.ReferenceEquals(this.fotoField, value) != true)) {
                    this.fotoField = value;
                    this.RaisePropertyChanged("foto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public System.Collections.ObjectModel.ObservableCollection<SilverlightApplication.DepartamentosServiceReference.departamento> departamentos {
            get {
                return this.departamentosField;
            }
            set {
                if ((object.ReferenceEquals(this.departamentosField, value) != true)) {
                    this.departamentosField = value;
                    this.RaisePropertyChanged("departamentos");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Binary", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Linq")]
    public partial class Binary : object, System.ComponentModel.INotifyPropertyChanged {
        
        private byte[] BytesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Bytes {
            get {
                return this.BytesField;
            }
            set {
                if ((object.ReferenceEquals(this.BytesField, value) != true)) {
                    this.BytesField = value;
                    this.RaisePropertyChanged("Bytes");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DepartamentosServiceReference.IDepartamentosService")]
    public interface IDepartamentosService {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IDepartamentosService/agregarNuevoDepartamento", ReplyAction="http://tempuri.org/IDepartamentosService/agregarNuevoDepartamentoResponse")]
        System.IAsyncResult BeginagregarNuevoDepartamento(SilverlightApplication.DepartamentosServiceReference.departamento nuevoDepartamento, System.AsyncCallback callback, object asyncState);
        
        bool EndagregarNuevoDepartamento(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IDepartamentosService/eliminarDepartamento", ReplyAction="http://tempuri.org/IDepartamentosService/eliminarDepartamentoResponse")]
        System.IAsyncResult BegineliminarDepartamento(int departamentoID, System.AsyncCallback callback, object asyncState);
        
        bool EndeliminarDepartamento(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IDepartamentosService/modificarDepartamento", ReplyAction="http://tempuri.org/IDepartamentosService/modificarDepartamentoResponse")]
        System.IAsyncResult BeginmodificarDepartamento(SilverlightApplication.DepartamentosServiceReference.departamento nuevoDepartamento, System.AsyncCallback callback, object asyncState);
        
        bool EndmodificarDepartamento(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IDepartamentosService/getDepartamentos", ReplyAction="http://tempuri.org/IDepartamentosService/getDepartamentosResponse")]
        System.IAsyncResult BegingetDepartamentos(System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<SilverlightApplication.DepartamentosServiceReference.departamento> EndgetDepartamentos(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IDepartamentosService/getDepartamento", ReplyAction="http://tempuri.org/IDepartamentosService/getDepartamentoResponse")]
        System.IAsyncResult BegingetDepartamento(int idDepto, System.AsyncCallback callback, object asyncState);
        
        SilverlightApplication.DepartamentosServiceReference.departamento EndgetDepartamento(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IDepartamentosService/getEstadisticas", ReplyAction="http://tempuri.org/IDepartamentosService/getEstadisticasResponse")]
        System.IAsyncResult BegingetEstadisticas(System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<SilverlightApplication.DepartamentosServiceReference.departamento> EndgetEstadisticas(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDepartamentosServiceChannel : SilverlightApplication.DepartamentosServiceReference.IDepartamentosService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class agregarNuevoDepartamentoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public agregarNuevoDepartamentoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class eliminarDepartamentoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public eliminarDepartamentoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class modificarDepartamentoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public modificarDepartamentoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getDepartamentosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public getDepartamentosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<SilverlightApplication.DepartamentosServiceReference.departamento> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<SilverlightApplication.DepartamentosServiceReference.departamento>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getDepartamentoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public getDepartamentoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public SilverlightApplication.DepartamentosServiceReference.departamento Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((SilverlightApplication.DepartamentosServiceReference.departamento)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getEstadisticasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public getEstadisticasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<SilverlightApplication.DepartamentosServiceReference.departamento> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<SilverlightApplication.DepartamentosServiceReference.departamento>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DepartamentosServiceClient : System.ServiceModel.ClientBase<SilverlightApplication.DepartamentosServiceReference.IDepartamentosService>, SilverlightApplication.DepartamentosServiceReference.IDepartamentosService {
        
        private BeginOperationDelegate onBeginagregarNuevoDepartamentoDelegate;
        
        private EndOperationDelegate onEndagregarNuevoDepartamentoDelegate;
        
        private System.Threading.SendOrPostCallback onagregarNuevoDepartamentoCompletedDelegate;
        
        private BeginOperationDelegate onBegineliminarDepartamentoDelegate;
        
        private EndOperationDelegate onEndeliminarDepartamentoDelegate;
        
        private System.Threading.SendOrPostCallback oneliminarDepartamentoCompletedDelegate;
        
        private BeginOperationDelegate onBeginmodificarDepartamentoDelegate;
        
        private EndOperationDelegate onEndmodificarDepartamentoDelegate;
        
        private System.Threading.SendOrPostCallback onmodificarDepartamentoCompletedDelegate;
        
        private BeginOperationDelegate onBegingetDepartamentosDelegate;
        
        private EndOperationDelegate onEndgetDepartamentosDelegate;
        
        private System.Threading.SendOrPostCallback ongetDepartamentosCompletedDelegate;
        
        private BeginOperationDelegate onBegingetDepartamentoDelegate;
        
        private EndOperationDelegate onEndgetDepartamentoDelegate;
        
        private System.Threading.SendOrPostCallback ongetDepartamentoCompletedDelegate;
        
        private BeginOperationDelegate onBegingetEstadisticasDelegate;
        
        private EndOperationDelegate onEndgetEstadisticasDelegate;
        
        private System.Threading.SendOrPostCallback ongetEstadisticasCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public DepartamentosServiceClient() {
        }
        
        public DepartamentosServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DepartamentosServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DepartamentosServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DepartamentosServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<agregarNuevoDepartamentoCompletedEventArgs> agregarNuevoDepartamentoCompleted;
        
        public event System.EventHandler<eliminarDepartamentoCompletedEventArgs> eliminarDepartamentoCompleted;
        
        public event System.EventHandler<modificarDepartamentoCompletedEventArgs> modificarDepartamentoCompleted;
        
        public event System.EventHandler<getDepartamentosCompletedEventArgs> getDepartamentosCompleted;
        
        public event System.EventHandler<getDepartamentoCompletedEventArgs> getDepartamentoCompleted;
        
        public event System.EventHandler<getEstadisticasCompletedEventArgs> getEstadisticasCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SilverlightApplication.DepartamentosServiceReference.IDepartamentosService.BeginagregarNuevoDepartamento(SilverlightApplication.DepartamentosServiceReference.departamento nuevoDepartamento, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginagregarNuevoDepartamento(nuevoDepartamento, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bool SilverlightApplication.DepartamentosServiceReference.IDepartamentosService.EndagregarNuevoDepartamento(System.IAsyncResult result) {
            return base.Channel.EndagregarNuevoDepartamento(result);
        }
        
        private System.IAsyncResult OnBeginagregarNuevoDepartamento(object[] inValues, System.AsyncCallback callback, object asyncState) {
            SilverlightApplication.DepartamentosServiceReference.departamento nuevoDepartamento = ((SilverlightApplication.DepartamentosServiceReference.departamento)(inValues[0]));
            return ((SilverlightApplication.DepartamentosServiceReference.IDepartamentosService)(this)).BeginagregarNuevoDepartamento(nuevoDepartamento, callback, asyncState);
        }
        
        private object[] OnEndagregarNuevoDepartamento(System.IAsyncResult result) {
            bool retVal = ((SilverlightApplication.DepartamentosServiceReference.IDepartamentosService)(this)).EndagregarNuevoDepartamento(result);
            return new object[] {
                    retVal};
        }
        
        private void OnagregarNuevoDepartamentoCompleted(object state) {
            if ((this.agregarNuevoDepartamentoCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.agregarNuevoDepartamentoCompleted(this, new agregarNuevoDepartamentoCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void agregarNuevoDepartamentoAsync(SilverlightApplication.DepartamentosServiceReference.departamento nuevoDepartamento) {
            this.agregarNuevoDepartamentoAsync(nuevoDepartamento, null);
        }
        
        public void agregarNuevoDepartamentoAsync(SilverlightApplication.DepartamentosServiceReference.departamento nuevoDepartamento, object userState) {
            if ((this.onBeginagregarNuevoDepartamentoDelegate == null)) {
                this.onBeginagregarNuevoDepartamentoDelegate = new BeginOperationDelegate(this.OnBeginagregarNuevoDepartamento);
            }
            if ((this.onEndagregarNuevoDepartamentoDelegate == null)) {
                this.onEndagregarNuevoDepartamentoDelegate = new EndOperationDelegate(this.OnEndagregarNuevoDepartamento);
            }
            if ((this.onagregarNuevoDepartamentoCompletedDelegate == null)) {
                this.onagregarNuevoDepartamentoCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnagregarNuevoDepartamentoCompleted);
            }
            base.InvokeAsync(this.onBeginagregarNuevoDepartamentoDelegate, new object[] {
                        nuevoDepartamento}, this.onEndagregarNuevoDepartamentoDelegate, this.onagregarNuevoDepartamentoCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SilverlightApplication.DepartamentosServiceReference.IDepartamentosService.BegineliminarDepartamento(int departamentoID, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegineliminarDepartamento(departamentoID, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bool SilverlightApplication.DepartamentosServiceReference.IDepartamentosService.EndeliminarDepartamento(System.IAsyncResult result) {
            return base.Channel.EndeliminarDepartamento(result);
        }
        
        private System.IAsyncResult OnBegineliminarDepartamento(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int departamentoID = ((int)(inValues[0]));
            return ((SilverlightApplication.DepartamentosServiceReference.IDepartamentosService)(this)).BegineliminarDepartamento(departamentoID, callback, asyncState);
        }
        
        private object[] OnEndeliminarDepartamento(System.IAsyncResult result) {
            bool retVal = ((SilverlightApplication.DepartamentosServiceReference.IDepartamentosService)(this)).EndeliminarDepartamento(result);
            return new object[] {
                    retVal};
        }
        
        private void OneliminarDepartamentoCompleted(object state) {
            if ((this.eliminarDepartamentoCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.eliminarDepartamentoCompleted(this, new eliminarDepartamentoCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void eliminarDepartamentoAsync(int departamentoID) {
            this.eliminarDepartamentoAsync(departamentoID, null);
        }
        
        public void eliminarDepartamentoAsync(int departamentoID, object userState) {
            if ((this.onBegineliminarDepartamentoDelegate == null)) {
                this.onBegineliminarDepartamentoDelegate = new BeginOperationDelegate(this.OnBegineliminarDepartamento);
            }
            if ((this.onEndeliminarDepartamentoDelegate == null)) {
                this.onEndeliminarDepartamentoDelegate = new EndOperationDelegate(this.OnEndeliminarDepartamento);
            }
            if ((this.oneliminarDepartamentoCompletedDelegate == null)) {
                this.oneliminarDepartamentoCompletedDelegate = new System.Threading.SendOrPostCallback(this.OneliminarDepartamentoCompleted);
            }
            base.InvokeAsync(this.onBegineliminarDepartamentoDelegate, new object[] {
                        departamentoID}, this.onEndeliminarDepartamentoDelegate, this.oneliminarDepartamentoCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SilverlightApplication.DepartamentosServiceReference.IDepartamentosService.BeginmodificarDepartamento(SilverlightApplication.DepartamentosServiceReference.departamento nuevoDepartamento, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginmodificarDepartamento(nuevoDepartamento, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bool SilverlightApplication.DepartamentosServiceReference.IDepartamentosService.EndmodificarDepartamento(System.IAsyncResult result) {
            return base.Channel.EndmodificarDepartamento(result);
        }
        
        private System.IAsyncResult OnBeginmodificarDepartamento(object[] inValues, System.AsyncCallback callback, object asyncState) {
            SilverlightApplication.DepartamentosServiceReference.departamento nuevoDepartamento = ((SilverlightApplication.DepartamentosServiceReference.departamento)(inValues[0]));
            return ((SilverlightApplication.DepartamentosServiceReference.IDepartamentosService)(this)).BeginmodificarDepartamento(nuevoDepartamento, callback, asyncState);
        }
        
        private object[] OnEndmodificarDepartamento(System.IAsyncResult result) {
            bool retVal = ((SilverlightApplication.DepartamentosServiceReference.IDepartamentosService)(this)).EndmodificarDepartamento(result);
            return new object[] {
                    retVal};
        }
        
        private void OnmodificarDepartamentoCompleted(object state) {
            if ((this.modificarDepartamentoCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.modificarDepartamentoCompleted(this, new modificarDepartamentoCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void modificarDepartamentoAsync(SilverlightApplication.DepartamentosServiceReference.departamento nuevoDepartamento) {
            this.modificarDepartamentoAsync(nuevoDepartamento, null);
        }
        
        public void modificarDepartamentoAsync(SilverlightApplication.DepartamentosServiceReference.departamento nuevoDepartamento, object userState) {
            if ((this.onBeginmodificarDepartamentoDelegate == null)) {
                this.onBeginmodificarDepartamentoDelegate = new BeginOperationDelegate(this.OnBeginmodificarDepartamento);
            }
            if ((this.onEndmodificarDepartamentoDelegate == null)) {
                this.onEndmodificarDepartamentoDelegate = new EndOperationDelegate(this.OnEndmodificarDepartamento);
            }
            if ((this.onmodificarDepartamentoCompletedDelegate == null)) {
                this.onmodificarDepartamentoCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnmodificarDepartamentoCompleted);
            }
            base.InvokeAsync(this.onBeginmodificarDepartamentoDelegate, new object[] {
                        nuevoDepartamento}, this.onEndmodificarDepartamentoDelegate, this.onmodificarDepartamentoCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SilverlightApplication.DepartamentosServiceReference.IDepartamentosService.BegingetDepartamentos(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegingetDepartamentos(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<SilverlightApplication.DepartamentosServiceReference.departamento> SilverlightApplication.DepartamentosServiceReference.IDepartamentosService.EndgetDepartamentos(System.IAsyncResult result) {
            return base.Channel.EndgetDepartamentos(result);
        }
        
        private System.IAsyncResult OnBegingetDepartamentos(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((SilverlightApplication.DepartamentosServiceReference.IDepartamentosService)(this)).BegingetDepartamentos(callback, asyncState);
        }
        
        private object[] OnEndgetDepartamentos(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<SilverlightApplication.DepartamentosServiceReference.departamento> retVal = ((SilverlightApplication.DepartamentosServiceReference.IDepartamentosService)(this)).EndgetDepartamentos(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetDepartamentosCompleted(object state) {
            if ((this.getDepartamentosCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getDepartamentosCompleted(this, new getDepartamentosCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getDepartamentosAsync() {
            this.getDepartamentosAsync(null);
        }
        
        public void getDepartamentosAsync(object userState) {
            if ((this.onBegingetDepartamentosDelegate == null)) {
                this.onBegingetDepartamentosDelegate = new BeginOperationDelegate(this.OnBegingetDepartamentos);
            }
            if ((this.onEndgetDepartamentosDelegate == null)) {
                this.onEndgetDepartamentosDelegate = new EndOperationDelegate(this.OnEndgetDepartamentos);
            }
            if ((this.ongetDepartamentosCompletedDelegate == null)) {
                this.ongetDepartamentosCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetDepartamentosCompleted);
            }
            base.InvokeAsync(this.onBegingetDepartamentosDelegate, null, this.onEndgetDepartamentosDelegate, this.ongetDepartamentosCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SilverlightApplication.DepartamentosServiceReference.IDepartamentosService.BegingetDepartamento(int idDepto, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegingetDepartamento(idDepto, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SilverlightApplication.DepartamentosServiceReference.departamento SilverlightApplication.DepartamentosServiceReference.IDepartamentosService.EndgetDepartamento(System.IAsyncResult result) {
            return base.Channel.EndgetDepartamento(result);
        }
        
        private System.IAsyncResult OnBegingetDepartamento(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int idDepto = ((int)(inValues[0]));
            return ((SilverlightApplication.DepartamentosServiceReference.IDepartamentosService)(this)).BegingetDepartamento(idDepto, callback, asyncState);
        }
        
        private object[] OnEndgetDepartamento(System.IAsyncResult result) {
            SilverlightApplication.DepartamentosServiceReference.departamento retVal = ((SilverlightApplication.DepartamentosServiceReference.IDepartamentosService)(this)).EndgetDepartamento(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetDepartamentoCompleted(object state) {
            if ((this.getDepartamentoCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getDepartamentoCompleted(this, new getDepartamentoCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getDepartamentoAsync(int idDepto) {
            this.getDepartamentoAsync(idDepto, null);
        }
        
        public void getDepartamentoAsync(int idDepto, object userState) {
            if ((this.onBegingetDepartamentoDelegate == null)) {
                this.onBegingetDepartamentoDelegate = new BeginOperationDelegate(this.OnBegingetDepartamento);
            }
            if ((this.onEndgetDepartamentoDelegate == null)) {
                this.onEndgetDepartamentoDelegate = new EndOperationDelegate(this.OnEndgetDepartamento);
            }
            if ((this.ongetDepartamentoCompletedDelegate == null)) {
                this.ongetDepartamentoCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetDepartamentoCompleted);
            }
            base.InvokeAsync(this.onBegingetDepartamentoDelegate, new object[] {
                        idDepto}, this.onEndgetDepartamentoDelegate, this.ongetDepartamentoCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SilverlightApplication.DepartamentosServiceReference.IDepartamentosService.BegingetEstadisticas(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegingetEstadisticas(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<SilverlightApplication.DepartamentosServiceReference.departamento> SilverlightApplication.DepartamentosServiceReference.IDepartamentosService.EndgetEstadisticas(System.IAsyncResult result) {
            return base.Channel.EndgetEstadisticas(result);
        }
        
        private System.IAsyncResult OnBegingetEstadisticas(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((SilverlightApplication.DepartamentosServiceReference.IDepartamentosService)(this)).BegingetEstadisticas(callback, asyncState);
        }
        
        private object[] OnEndgetEstadisticas(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<SilverlightApplication.DepartamentosServiceReference.departamento> retVal = ((SilverlightApplication.DepartamentosServiceReference.IDepartamentosService)(this)).EndgetEstadisticas(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetEstadisticasCompleted(object state) {
            if ((this.getEstadisticasCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getEstadisticasCompleted(this, new getEstadisticasCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getEstadisticasAsync() {
            this.getEstadisticasAsync(null);
        }
        
        public void getEstadisticasAsync(object userState) {
            if ((this.onBegingetEstadisticasDelegate == null)) {
                this.onBegingetEstadisticasDelegate = new BeginOperationDelegate(this.OnBegingetEstadisticas);
            }
            if ((this.onEndgetEstadisticasDelegate == null)) {
                this.onEndgetEstadisticasDelegate = new EndOperationDelegate(this.OnEndgetEstadisticas);
            }
            if ((this.ongetEstadisticasCompletedDelegate == null)) {
                this.ongetEstadisticasCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetEstadisticasCompleted);
            }
            base.InvokeAsync(this.onBegingetEstadisticasDelegate, null, this.onEndgetEstadisticasDelegate, this.ongetEstadisticasCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override SilverlightApplication.DepartamentosServiceReference.IDepartamentosService CreateChannel() {
            return new DepartamentosServiceClientChannel(this);
        }
        
        private class DepartamentosServiceClientChannel : ChannelBase<SilverlightApplication.DepartamentosServiceReference.IDepartamentosService>, SilverlightApplication.DepartamentosServiceReference.IDepartamentosService {
            
            public DepartamentosServiceClientChannel(System.ServiceModel.ClientBase<SilverlightApplication.DepartamentosServiceReference.IDepartamentosService> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginagregarNuevoDepartamento(SilverlightApplication.DepartamentosServiceReference.departamento nuevoDepartamento, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = nuevoDepartamento;
                System.IAsyncResult _result = base.BeginInvoke("agregarNuevoDepartamento", _args, callback, asyncState);
                return _result;
            }
            
            public bool EndagregarNuevoDepartamento(System.IAsyncResult result) {
                object[] _args = new object[0];
                bool _result = ((bool)(base.EndInvoke("agregarNuevoDepartamento", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BegineliminarDepartamento(int departamentoID, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = departamentoID;
                System.IAsyncResult _result = base.BeginInvoke("eliminarDepartamento", _args, callback, asyncState);
                return _result;
            }
            
            public bool EndeliminarDepartamento(System.IAsyncResult result) {
                object[] _args = new object[0];
                bool _result = ((bool)(base.EndInvoke("eliminarDepartamento", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginmodificarDepartamento(SilverlightApplication.DepartamentosServiceReference.departamento nuevoDepartamento, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = nuevoDepartamento;
                System.IAsyncResult _result = base.BeginInvoke("modificarDepartamento", _args, callback, asyncState);
                return _result;
            }
            
            public bool EndmodificarDepartamento(System.IAsyncResult result) {
                object[] _args = new object[0];
                bool _result = ((bool)(base.EndInvoke("modificarDepartamento", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BegingetDepartamentos(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("getDepartamentos", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<SilverlightApplication.DepartamentosServiceReference.departamento> EndgetDepartamentos(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<SilverlightApplication.DepartamentosServiceReference.departamento> _result = ((System.Collections.ObjectModel.ObservableCollection<SilverlightApplication.DepartamentosServiceReference.departamento>)(base.EndInvoke("getDepartamentos", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BegingetDepartamento(int idDepto, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = idDepto;
                System.IAsyncResult _result = base.BeginInvoke("getDepartamento", _args, callback, asyncState);
                return _result;
            }
            
            public SilverlightApplication.DepartamentosServiceReference.departamento EndgetDepartamento(System.IAsyncResult result) {
                object[] _args = new object[0];
                SilverlightApplication.DepartamentosServiceReference.departamento _result = ((SilverlightApplication.DepartamentosServiceReference.departamento)(base.EndInvoke("getDepartamento", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BegingetEstadisticas(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("getEstadisticas", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<SilverlightApplication.DepartamentosServiceReference.departamento> EndgetEstadisticas(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<SilverlightApplication.DepartamentosServiceReference.departamento> _result = ((System.Collections.ObjectModel.ObservableCollection<SilverlightApplication.DepartamentosServiceReference.departamento>)(base.EndInvoke("getEstadisticas", _args, result)));
                return _result;
            }
        }
    }
}
