#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TareaServiceWebRole
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.Runtime.Serialization;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SQL_Azure")]
	public partial class TareaDataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertdepartamento(departamento instance);
    partial void Updatedepartamento(departamento instance);
    partial void Deletedepartamento(departamento instance);
    partial void Insertempleado(empleado instance);
    partial void Updateempleado(empleado instance);
    partial void Deleteempleado(empleado instance);
    #endregion
		
		public TareaDataClassesDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["SQL_AzureConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public TareaDataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TareaDataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TareaDataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TareaDataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<departamento> departamentos
		{
			get
			{
				return this.GetTable<departamento>();
			}
		}
		
		public System.Data.Linq.Table<empleado> empleados
		{
			get
			{
				return this.GetTable<empleado>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="proyecto.SP_getEmpleadosDepartamento")]
		public ISingleResult<SP_getEmpleadosDepartamentoResult> SP_getEmpleadosDepartamento([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pIdDepto)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pIdDepto);
			return ((ISingleResult<SP_getEmpleadosDepartamentoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="proyecto.SP_getEmpleadosDepartamentoAno")]
		public ISingleResult<SP_getEmpleadosDepartamentoAnoResult> SP_getEmpleadosDepartamentoAno()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SP_getEmpleadosDepartamentoAnoResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="proyecto.departamentos")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class departamento : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idDepto;
		
		private string _nbrDepto;
		
		private System.Nullable<int> _idEncargado;
		
		private string _ubicacion;
		
		private EntitySet<empleado> _empleados;
		
		private EntityRef<empleado> _empleado;
		
		private bool serializing;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidDeptoChanging(int value);
    partial void OnidDeptoChanged();
    partial void OnnbrDeptoChanging(string value);
    partial void OnnbrDeptoChanged();
    partial void OnidEncargadoChanging(System.Nullable<int> value);
    partial void OnidEncargadoChanged();
    partial void OnubicacionChanging(string value);
    partial void OnubicacionChanged();
    #endregion
		
		public departamento()
		{
			this.Initialize();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idDepto", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public int idDepto
		{
			get
			{
				return this._idDepto;
			}
			set
			{
				if ((this._idDepto != value))
				{
					this.OnidDeptoChanging(value);
					this.SendPropertyChanging();
					this._idDepto = value;
					this.SendPropertyChanged("idDepto");
					this.OnidDeptoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nbrDepto", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public string nbrDepto
		{
			get
			{
				return this._nbrDepto;
			}
			set
			{
				if ((this._nbrDepto != value))
				{
					this.OnnbrDeptoChanging(value);
					this.SendPropertyChanging();
					this._nbrDepto = value;
					this.SendPropertyChanged("nbrDepto");
					this.OnnbrDeptoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idEncargado", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=3)]
		public System.Nullable<int> idEncargado
		{
			get
			{
				return this._idEncargado;
			}
			set
			{
				if ((this._idEncargado != value))
				{
					if (this._empleado.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidEncargadoChanging(value);
					this.SendPropertyChanging();
					this._idEncargado = value;
					this.SendPropertyChanged("idEncargado");
					this.OnidEncargadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ubicacion", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=4)]
		public string ubicacion
		{
			get
			{
				return this._ubicacion;
			}
			set
			{
				if ((this._ubicacion != value))
				{
					this.OnubicacionChanging(value);
					this.SendPropertyChanging();
					this._ubicacion = value;
					this.SendPropertyChanged("ubicacion");
					this.OnubicacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="departamento_empleado", Storage="_empleados", ThisKey="idDepto", OtherKey="idDepto")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=5, EmitDefaultValue=false)]
		public EntitySet<empleado> empleados
		{
			get
			{
				if ((this.serializing 
							&& (this._empleados.HasLoadedOrAssignedValues == false)))
				{
					return null;
				}
				return this._empleados;
			}
			set
			{
				this._empleados.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="empleado_departamento", Storage="_empleado", ThisKey="idEncargado", OtherKey="idEmpleado", IsForeignKey=true)]
		public empleado empleado
		{
			get
			{
				return this._empleado.Entity;
			}
			set
			{
				empleado previousValue = this._empleado.Entity;
				if (((previousValue != value) 
							|| (this._empleado.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._empleado.Entity = null;
						previousValue.departamentos.Remove(this);
					}
					this._empleado.Entity = value;
					if ((value != null))
					{
						value.departamentos.Add(this);
						this._idEncargado = value.idEmpleado;
					}
					else
					{
						this._idEncargado = default(Nullable<int>);
					}
					this.SendPropertyChanged("empleado");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_empleados(empleado entity)
		{
			this.SendPropertyChanging();
			entity.departamento = this;
		}
		
		private void detach_empleados(empleado entity)
		{
			this.SendPropertyChanging();
			entity.departamento = null;
		}
		
		private void Initialize()
		{
			this._empleados = new EntitySet<empleado>(new Action<empleado>(this.attach_empleados), new Action<empleado>(this.detach_empleados));
			this._empleado = default(EntityRef<empleado>);
			OnCreated();
		}
		
		[global::System.Runtime.Serialization.OnDeserializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnDeserializing(StreamingContext context)
		{
			this.Initialize();
		}
		
		[global::System.Runtime.Serialization.OnSerializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnSerializing(StreamingContext context)
		{
			this.serializing = true;
		}
		
		[global::System.Runtime.Serialization.OnSerializedAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnSerialized(StreamingContext context)
		{
			this.serializing = false;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="proyecto.empleados")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class empleado : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idEmpleado;
		
		private string _nbrEmpleado;
		
		private System.Nullable<int> _idDepto;
		
		private System.DateTime _fechaIngreso;
		
		private System.Data.Linq.Binary _foto;
		
		private EntitySet<departamento> _departamentos;
		
		private EntityRef<departamento> _departamento;
		
		private bool serializing;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidEmpleadoChanging(int value);
    partial void OnidEmpleadoChanged();
    partial void OnnbrEmpleadoChanging(string value);
    partial void OnnbrEmpleadoChanged();
    partial void OnidDeptoChanging(System.Nullable<int> value);
    partial void OnidDeptoChanged();
    partial void OnfechaIngresoChanging(System.DateTime value);
    partial void OnfechaIngresoChanged();
    partial void OnfotoChanging(System.Data.Linq.Binary value);
    partial void OnfotoChanged();
    #endregion
		
		public empleado()
		{
			this.Initialize();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idEmpleado", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public int idEmpleado
		{
			get
			{
				return this._idEmpleado;
			}
			set
			{
				if ((this._idEmpleado != value))
				{
					this.OnidEmpleadoChanging(value);
					this.SendPropertyChanging();
					this._idEmpleado = value;
					this.SendPropertyChanged("idEmpleado");
					this.OnidEmpleadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nbrEmpleado", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public string nbrEmpleado
		{
			get
			{
				return this._nbrEmpleado;
			}
			set
			{
				if ((this._nbrEmpleado != value))
				{
					this.OnnbrEmpleadoChanging(value);
					this.SendPropertyChanging();
					this._nbrEmpleado = value;
					this.SendPropertyChanged("nbrEmpleado");
					this.OnnbrEmpleadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idDepto", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=3)]
		public System.Nullable<int> idDepto
		{
			get
			{
				return this._idDepto;
			}
			set
			{
				if ((this._idDepto != value))
				{
					if (this._departamento.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidDeptoChanging(value);
					this.SendPropertyChanging();
					this._idDepto = value;
					this.SendPropertyChanged("idDepto");
					this.OnidDeptoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaIngreso", DbType="DateTime NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=4)]
		public System.DateTime fechaIngreso
		{
			get
			{
				return this._fechaIngreso;
			}
			set
			{
				if ((this._fechaIngreso != value))
				{
					this.OnfechaIngresoChanging(value);
					this.SendPropertyChanging();
					this._fechaIngreso = value;
					this.SendPropertyChanged("fechaIngreso");
					this.OnfechaIngresoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_foto", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=5)]
		public System.Data.Linq.Binary foto
		{
			get
			{
				return this._foto;
			}
			set
			{
				if ((this._foto != value))
				{
					this.OnfotoChanging(value);
					this.SendPropertyChanging();
					this._foto = value;
					this.SendPropertyChanged("foto");
					this.OnfotoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="empleado_departamento", Storage="_departamentos", ThisKey="idEmpleado", OtherKey="idEncargado")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=6, EmitDefaultValue=false)]
		public EntitySet<departamento> departamentos
		{
			get
			{
				if ((this.serializing 
							&& (this._departamentos.HasLoadedOrAssignedValues == false)))
				{
					return null;
				}
				return this._departamentos;
			}
			set
			{
				this._departamentos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="departamento_empleado", Storage="_departamento", ThisKey="idDepto", OtherKey="idDepto", IsForeignKey=true)]
		public departamento departamento
		{
			get
			{
				return this._departamento.Entity;
			}
			set
			{
				departamento previousValue = this._departamento.Entity;
				if (((previousValue != value) 
							|| (this._departamento.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._departamento.Entity = null;
						previousValue.empleados.Remove(this);
					}
					this._departamento.Entity = value;
					if ((value != null))
					{
						value.empleados.Add(this);
						this._idDepto = value.idDepto;
					}
					else
					{
						this._idDepto = default(Nullable<int>);
					}
					this.SendPropertyChanged("departamento");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_departamentos(departamento entity)
		{
			this.SendPropertyChanging();
			entity.empleado = this;
		}
		
		private void detach_departamentos(departamento entity)
		{
			this.SendPropertyChanging();
			entity.empleado = null;
		}
		
		private void Initialize()
		{
			this._departamentos = new EntitySet<departamento>(new Action<departamento>(this.attach_departamentos), new Action<departamento>(this.detach_departamentos));
			this._departamento = default(EntityRef<departamento>);
			OnCreated();
		}
		
		[global::System.Runtime.Serialization.OnDeserializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnDeserializing(StreamingContext context)
		{
			this.Initialize();
		}
		
		[global::System.Runtime.Serialization.OnSerializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnSerializing(StreamingContext context)
		{
			this.serializing = true;
		}
		
		[global::System.Runtime.Serialization.OnSerializedAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnSerialized(StreamingContext context)
		{
			this.serializing = false;
		}
	}
	
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class SP_getEmpleadosDepartamentoResult
	{
		
		private int _idEmpleado;
		
		private string _nbrEmpleado;
		
		private System.Nullable<int> _idDepto;
		
		private System.DateTime _fechaIngreso;
		
		private System.Data.Linq.Binary _foto;
		
		public SP_getEmpleadosDepartamentoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idEmpleado", DbType="Int NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public int idEmpleado
		{
			get
			{
				return this._idEmpleado;
			}
			set
			{
				if ((this._idEmpleado != value))
				{
					this._idEmpleado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nbrEmpleado", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public string nbrEmpleado
		{
			get
			{
				return this._nbrEmpleado;
			}
			set
			{
				if ((this._nbrEmpleado != value))
				{
					this._nbrEmpleado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idDepto", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=3)]
		public System.Nullable<int> idDepto
		{
			get
			{
				return this._idDepto;
			}
			set
			{
				if ((this._idDepto != value))
				{
					this._idDepto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaIngreso", DbType="DateTime NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=4)]
		public System.DateTime fechaIngreso
		{
			get
			{
				return this._fechaIngreso;
			}
			set
			{
				if ((this._fechaIngreso != value))
				{
					this._fechaIngreso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_foto", DbType="Image")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=5)]
		public System.Data.Linq.Binary foto
		{
			get
			{
				return this._foto;
			}
			set
			{
				if ((this._foto != value))
				{
					this._foto = value;
				}
			}
		}
	}
	
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class SP_getEmpleadosDepartamentoAnoResult
	{
		
		private System.Nullable<int> _ano;
		
		private System.Nullable<int> _cantEmpleados;
		
		private System.Nullable<int> _idDepto;
		
		public SP_getEmpleadosDepartamentoAnoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ano", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public System.Nullable<int> ano
		{
			get
			{
				return this._ano;
			}
			set
			{
				if ((this._ano != value))
				{
					this._ano = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cantEmpleados", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public System.Nullable<int> cantEmpleados
		{
			get
			{
				return this._cantEmpleados;
			}
			set
			{
				if ((this._cantEmpleados != value))
				{
					this._cantEmpleados = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idDepto", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=3)]
		public System.Nullable<int> idDepto
		{
			get
			{
				return this._idDepto;
			}
			set
			{
				if ((this._idDepto != value))
				{
					this._idDepto = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
